repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff-check  # linting
        files: ^(src/ifes_apt_tc_data_modeling|tests)/.*\.py$
      - id: ruff-format
        files: ^(src/ifes_apt_tc_data_modeling|tests)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy  # static type checking

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]  # modernizes syntax for Python 3.6+

  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.9.0
  #   hooks:
  #     - id: nbstripout  # removes notebook outputs before committing

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.4.0
    hooks:
      - id: cspell  # spellchecking
        pass_filenames: false
        args:
          - --config
          - cspell.json
          - README.md
          - CITATION.cff
          - docs/**/*
          - src/ifes_apt_tc_data_modeling/**/*.py
          - tests/**/*.py
