name: linting

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install uv and set the python version to ${{ matrix.python_version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install package and dev dependencies
        run: |
          uv pip install ".[dev]"
      - name: ruff check
        run: |
          ruff check src/ifes_apt_tc_data_modeling tests
      - name: ruff format
        run: |
          ruff format --check src/ifes_apt_tc_data_modeling tests
      - name: mypy
        run: |
          mypy src/ifes_apt_tc_data_modeling tests
